### ISSUE TITLE
v0.10.0 compatibility issue with jsonrpc2 v0.9.0

### ISSUE THREAD

**Issue by ConnorPickles** [go-language-server/protocol#22]
At handler_json.go:47, `id` is cast using `int64(id)` instead of `int32(id)`, causing an error since jsonrpc2 is expecting `int32` at wire.go:60.

Not sure which package is correct. Happy to create a PR to fix this, but didn't want to be presumptuous.

**Comment by slzatz** [comment]
I've tried to fork the directory and change go.mod to point at the fork until this is fixed but somehow even with go.mod changed, it's still looking for go.lsp.dev/protocol.  Anyone with more go experience have any advice?

**Comment by ConnorPickles** [comment]
@zchee Is this something you have time to quickly fix?

**Comment by zchee** [comment]
@ConnorPickles @slzatz Sorry for the late reply.

I develop into https://github.com/go-language-server/protocol/pull/21, which supported jsonrpc2 v0.9.0.

I’d testing that PR’s branch internally. It seems no issue to following vscode-languageserver-node upstream change.
Will merge above PR and cut new version later.
Sorry for confused you.

**Comment by ConnorPickles** [comment]
Glad to know a fix is coming, saves me from having to fork and host it myself! Thanks for the update.

**Comment by zchee** [comment]
@slzatz @ConnorPickles merged
