### ISSUE TITLE
francoispqt/gojay is not actively maintained which causes dependabot to fail

### ISSUE THREAD

**Issue by blkperl** [go-language-server/protocol#31]
gojay hasn't had a release since 2019. https://github.com/francoispqt/gojay/issues/150

Since the 2019 gojay release, thrift has moved the repository to github.com/apache/thrift which has been fixed in newer versions of go.opencensus.io and cloud.google.com/go but since gojay is unmaintained those new dependencies have not been pulled into gojay or this project which means Dependabot fails when trying to update skaffold. 

Reference: https://github.com/census-instrumentation/opencensus-go/issues/1158#issuecomment-531542799

```
Dependabot encountered the following error:

go: github.com/GoogleContainerTools/skaffold@v1.35.0 requires
	go.lsp.dev/protocol@v0.11.2 requires
	github.com/francoispqt/gojay@v1.2.13 requires
	cloud.google.com/go@v0.37.0 requires
	go.opencensus.io@v0.18.0 requires
	git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: invalid version: unknown revisio
```

**Comment by zchee** [comment]
@blkperl removed gojay on https://github.com/go-language-server/protocol/releases/tag/v0.12.0

**Comment by blkperl** [comment]
Awesome! Thanks
