### ISSUE TITLE
Move vscode snippets to go language server

### ISSUE THREAD

**Issue by angelozerr** [go-language-server/protocol#50]
It would be really nice if Go language server could embed the vscode snippets https://github.com/golang/vscode-go/blob/master/extension/snippets/go.json in order to another LSP client like Eclipse IDE, IJ will benefit with this very helpful snippets.

Thanks!

**Comment by rcjsuen** [comment]
@angelozerr I think you meant to open this issue with the gopls project in [golang/tools](https://github.com/golang/tools). This repository provides an API for implementing language servers in Go and _not_ related to the Go language server (named "gopls") for integration with LSP clients.

**Comment by angelozerr** [comment]
Ooops sorry, indeed I wanted to say that.

**Comment by zchee** [comment]
@angelozerr Can I close?

**Comment by angelozerr** [comment]
Yes we need to move this issue to go language server
